config/routes.rb
Rails.application.routes.draw do
  get 'usertasks/create'

  resources :tasks, only: :index do
    resources :usertasks, only: [:create, :destroy]
  end

  resources :usertasks, only: :index

  root to: 'tasks#index'
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

  has_many :usertasks
  has_many :users, through: :usertasks

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :usertasks
  has_many :tasks, through: :usertasks
end

app/models/usertask.rb
class Usertask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = Task.all
  end

  def show
    @task = Task.find(params[:id])
    @ranking5 = Usertask.limit(5).where(task_id: @task.id).order(created_at: :asc)
    @users_todo_finish = Usertask.all.where(task_id: @task.id).order(created_at: :asc)
  end
end

app/controllers/usertasks_controller.rb
class UsertasksController < ApplicationController
  before_action :authenticate_user!
  def create

    @task = Task.find(params[:task_id])
    @usertasks = Usertask.new(task: @task, user: current_user,  completado: true)
    if @usertasks.save
      redirect_to tasks_path, notice: 'la tarea ha sido realizada'
    else
      redirect_to tasks_path, alert: 'la tarea no ha sido realizada'
    end
  end

  def destroy
    @task = Task.find(params[:task_id])
    @usertasks = Usertask.find_by(task: @task, user: current_user.id)
      @usertasks.destroy
        redirect_to tasks_path
      end

  def index
    @usertasks = current_user.usertasks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def existe_tarea_usuario?(task)
      e = task.usertasks.where(user_id: current_user.id)
      if e.count > 0
        true
      else
        false
      end
  end
end

app/helpers/usertasks_helper.rb
module UsertasksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href=" <%= tasks_path %> ">ToDo 18 Sep</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if user_signed_in? %>
      <a class="nav-item nav-link active" href=" <%= usertasks_path %> "> Detalles <span class="sr-only">(current)</span></a>
      <a class="nav-link" href="#">Completados <%=
        Usertask.where(user_id: current_user.id, completado: true).count
        %> / <%= Task.all.count %><span
        class="sr-only">(current)</span></a>
        <%= link_to 'Salir', destroy_user_session_path, method: :DELETE, class: 'nav-item nav-link' %>

      <% else %>
      <a class="nav-item nav-link active" href="<%= new_user_session_path %>"> Ingresar <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href=" <%= new_user_registration_path %> "> Registro </a>

      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo18sep</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>
    
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <% @task.each do |task| %>
    <div class="col-3">
      <div class="card" style="margin:10px">
        <%= image_tag task.photo, class: 'card-img-top' %>
        <div class="body">
          <h5><%= task.name %></h5>
          <% if user_signed_in? %>
            <% if existe_tarea_usuario?(task) %>
              <%= link_to "Cancelar", task_usertask_path(task, current_user), class: 'btn btn-success btn-blocks', method: :delete%>
            <% else %>
              <%= link_to "Completar", task_usertasks_path(task), class: 'btn btn-success btn-blocks', method: :post %>
            <% end %>
          <% else %>
          <a class="nav-item nav-link active" href="<%= new_user_session_path %>"> Ingresar <span class="sr-only">(current)</span></a>
          <% end %>

        </div>
      </div>
    </div>
    <% end %>
    <div class="w-100" style="margin:10px"> </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class>
  <div class="card mx-auto my-4" style="width: 18rem;">
    <h3><%= @task.name %></h3>
    <%= image_tag @task.photo, class: "card-img-top" %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col 6">
      <table class="table">
        <thead>
            <h2>Top 5</h2>
          <tr>
            <th scope="col">Usuario</th>
            <th scope="col">Fecha realizada</th>
          </tr>
        </thead>
        <tbody>
          <% @ranking5.each do |rank| %>
            <tr>
              <td><%= User.find_by(id: rank.user_id).name %></td>
              <td><%= rank.created_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col 6">
      <h2>Usuarios que han realizado la tarea</h2>
      <ul class="list-group">
        <% @users_todo_finish.each do |user| %>
        <li class="list-group-item"><%= User.find_by(id: user.user_id).name %> </li>
        <% end %>
      </ul>
    </div>

  </div>
</div>

app/views/usertasks/index.html.erb
<div class="container">
  <table class="table">
    <% @usertasks.each do |usertask| %>
    <tr>
      <ul>
        <td><li value="1"><%= usertask.task.name %></li></td>
      </ul>
    </tr>
    <% end %>
  </table>
</div>